
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'SleftPLUSMINUSAND ASSIGNMENT ASTERISK BOOL CHAR FLOAT FOR FWSLASH GREATER GREATER_EQUAL INT IS_EQUAL LESSER LESSER_EQUAL MINUS MINUS_MINUS MOD NOT NOT_EQUAL OR PLUS PLUS_PLUS PRINT SEMICOL STRING TOPI VAR_NAME\n    S : stmt S\n    \n    S :\n    \n    stmt : PRINT exp SEMICOL\n     \n    exp : exp PLUS exp\n        | exp MINUS exp\n    \n    exp : INT\n    '
    
_lr_action_items = {'$end':([0,1,2,4,7,],[-2,0,-2,-1,-3,]),'PRINT':([0,2,7,],[3,3,-3,]),'INT':([3,8,9,],[6,6,6,]),'SEMICOL':([5,6,10,11,],[7,-6,-4,-5,]),'PLUS':([5,6,10,11,],[8,-6,-4,-5,]),'MINUS':([5,6,10,11,],[9,-6,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,2,],[1,4,]),'stmt':([0,2,],[2,2,]),'exp':([3,8,9,],[5,10,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> stmt S','S',2,'p_start','yapl_parser.py',19),
  ('S -> <empty>','S',0,'p_start_empty','yapl_parser.py',26),
  ('stmt -> PRINT exp SEMICOL','stmt',3,'p_print_stmt','yapl_parser.py',33),
  ('exp -> exp PLUS exp','exp',3,'p_exp_bin','yapl_parser.py',40),
  ('exp -> exp MINUS exp','exp',3,'p_exp_bin','yapl_parser.py',41),
  ('exp -> INT','exp',1,'p_exp_num','yapl_parser.py',48),
]
